name: ArmoredElytra
main: nl.pim16aap2.armoredElytra.ArmoredElytra
version: ${project.version}
author: pim16aap2
softdepend: [ AdvancedEnchantments ]
api-version: 1.16
folia-supported: true
commands:
  ArmoredElytra:
    description: 給予指定階級的羽裝。
    usage: /ArmoredElytra [接收者] <階級>
permissions:
  armoredelytra.wear.leather:
    description: 允許玩家穿戴素革羽裝。
  armoredelytra.wear.gold:
    description: 允許玩家穿戴山吹金羽裝。
  armoredelytra.wear.chain:
    description: 允許玩家穿戴銀鎖羽裝。
  armoredelytra.wear.iron:
    description: 允許玩家穿戴玉鋼羽裝。
  armoredelytra.wear.diamond:
    description: 允許玩家穿戴青金剛羽裝。
  armoredelytra.wear.netherite:
    description: 允許玩家穿戴彼岸獄羽。
  armoredelytra.wear.copper:
    description: 允許玩家穿戴赤銅羽裝。
  armoredelytra.craft.leather:
    description: 允許玩家鍛造素革羽裝。
  armoredelytra.craft.gold:
    description: 允許玩家鍛造山吹金羽裝。
  armoredelytra.craft.chain:
    description: 允許玩家鍛造銀鎖羽裝。
  armoredelytra.craft.iron:
    description: 允許玩家鍛造玉鋼羽裝。
  armoredelytra.craft.diamond:
    description: 允許玩家鍛造青金剛羽裝。
  armoredelytra.craft.netherite:
    description: 允許玩家鍛造彼岸獄羽。
  armoredelytra.craft.copper:
    description: 允許玩家鍛造赤銅羽裝。
  armoredelytra.give.leather:
    description: 允許給予玩家素革羽裝。
  armoredelytra.give.gold:
    description: 允許給予玩家山吹金羽裝。
  armoredelytra.give.chain:
    description: 允許給予玩家銀鎖羽裝。
  armoredelytra.give.iron:
    description: 允許給予玩家玉鋼羽裝。
  armoredelytra.give.diamond:
    description: 允許給予玩家青金剛羽裝。
  armoredelytra.give.netherite:
    description: 允許給予玩家彼岸獄羽。
  armoredelytra.give.copper:
    description: 允許給予玩家赤銅羽裝。
  armoredElytra.admin:
    description: 登入伺服器時接收插件更新提示。
